/** Hindi and Marathi chrome drafts; native speaker review required. */
export const chromeHindiMarathi = {
  hi: {
    'chrome.marketplace':'मार्केटप्लेस','chrome.wiki':'विकी','chrome.pricing':'कीमतें','chrome.ideas':'विचार','chrome.bazaar':'बाज़ार','chrome.creators':'क्रिएटर्स','chrome.company':'कंपनी','chrome.explore':'देखें','chrome.liveStreaming':'लाइव स्ट्रीमिंग','chrome.findPeople':'अपने लोग खोजें','chrome.exploreMarketplace':'मार्केटप्लेस देखें','chrome.startSelling':'बेचना शुरू करें','chrome.creatorDashboard':'क्रिएटर डैशबोर्ड','chrome.payouts':'भुगतान','chrome.safety':'सुरक्षा','chrome.about':'हमारे बारे में','chrome.careers':'करियर','chrome.contact':'संपर्क','chrome.privacy':'गोपनीयता नीति','chrome.cookies':'कुकीज़','chrome.refunds':'रिफंड','chrome.marketplaceTerms':'मार्केटप्लेस की शर्तें','chrome.consultationTerms':'परामर्श की शर्तें','chrome.acceptableUse':'स्वीकार्य उपयोग','chrome.recordingConsent':'रिकॉर्डिंग और सहमति','chrome.biometricData':'बायोमेट्रिक जानकारी','chrome.dmca':'DMCA','chrome.communityGuidelines':'सामुदायिक दिशानिर्देश','chrome.childSafety':'बाल सुरक्षा','chrome.grievance':'शिकायत निवारण','chrome.contactReport':'संपर्क और रिपोर्ट','chrome.pricingFees':'कीमत और शुल्क','chrome.tokensWallet':'टोकन और वॉलेट','chrome.tagline':'भारत का लाइव क्रिएटर बाज़ार। एक सीट बुक करें और साथ समय बिताएँ।','chrome.voice':'आपकी आवाज़ दुनिया तक।','chrome.goodbye':'अभी विदा, फिर मिलेंगे।','chrome.comeAgain':'फिर आइए।','chrome.roadMotto':'सुरक्षित ड्राइव करें।','chrome.madeWith':'प्यार और कटिंग चाय के साथ बनाया गया।',
  },
  mr: {
    'chrome.marketplace':'मार्केटप्लेस','chrome.wiki':'विकी','chrome.pricing':'दर','chrome.ideas':'कल्पना','chrome.bazaar':'बाजार','chrome.creators':'निर्माते','chrome.company':'कंपनी','chrome.explore':'भटकंती करा','chrome.liveStreaming':'थेट प्रसारण','chrome.findPeople':'आपली माणसं शोधा','chrome.exploreMarketplace':'मार्केटप्लेस पाहा','chrome.startSelling':'विक्री सुरू करा','chrome.creatorDashboard':'निर्माता डॅशबोर्ड','chrome.payouts':'पैसे मिळवा','chrome.safety':'सुरक्षितता','chrome.about':'आमच्याबद्दल','chrome.careers':'कारकीर्द','chrome.contact':'संपर्क','chrome.privacy':'गोपनीयता धोरण','chrome.cookies':'कुकीज','chrome.refunds':'परतावा','chrome.marketplaceTerms':'मार्केटप्लेसच्या अटी','chrome.consultationTerms':'सल्ला सेवेच्या अटी','chrome.acceptableUse':'मान्य वापर','chrome.recordingConsent':'रेकॉर्डिंग व संमती','chrome.biometricData':'बायोमेट्रिक माहिती','chrome.dmca':'DMCA','chrome.communityGuidelines':'समुदाय मार्गदर्शक तत्त्वे','chrome.childSafety':'बालसुरक्षा','chrome.grievance':'तक्रार निवारण','chrome.contactReport':'संपर्क व अहवाल','chrome.pricingFees':'दर व शुल्क','chrome.tokensWallet':'टोकन व पाकीट','chrome.tagline':'भारताचा थेट निर्माता बाजार. एक आसन आरक्षित करा आणि सोबत वेळ घालवा.','chrome.voice':'तुमचा आवाज जगापर्यंत पोहोचवा.','chrome.goodbye':'आत्तासाठी निरोप, पुन्हा भेटू.','chrome.comeAgain':'पुन्हा या.','chrome.roadMotto':'सुरक्षित वाहन चालवा.','chrome.madeWith':'प्रेम आणि कटिंग चहाने बनवलेले.',
  },
} as const;
