export const chromeRegionalRtl = {
kok: {
'chrome.marketplace':'मार्केटप्लेस','chrome.wiki':'विकी','chrome.pricing':'मोल','chrome.ideas':'कल्पना','chrome.bazaar':'बाजार','chrome.creators':'निर्माते','chrome.company':'कंपनी','chrome.explore':'शोधात','chrome.liveStreaming':'लायव्ह स्ट्रीमिंग','chrome.findPeople':'लोक सोदात','chrome.exploreMarketplace':'मार्केटप्लेस पळयात','chrome.startSelling':'विकप सुरू करात','chrome.creatorDashboard':'निर्मातो डॅशबोर्ड','chrome.payouts':'फारीक मेळोवप','chrome.safety':'सुरक्षीतपण','chrome.about':'आमचे विशीं','chrome.careers':'नोकरीची संधी','chrome.contact':'संपर्क','chrome.privacy':'खाजगीपण','chrome.cookies':'कुकीज','chrome.refunds':'फारीक दियात','chrome.marketplaceTerms':'मार्केटप्लेस अटी','chrome.consultationTerms':'सल्ल्याच्या अटी','chrome.acceptableUse':'मान्य वापर','chrome.recordingConsent':'रेकॉर्डिंग मान्यता','chrome.biometricData':'बायोमेट्रिक माहिती','chrome.dmca':'DMCA कळोवणी','chrome.communityGuidelines':'समुदाय मार्गदर्शक','chrome.childSafety':'भुरग्यांची सुरक्षीतपण','chrome.grievance':'तक्रार','chrome.contactReport':'संपर्क आनी रिपोर्ट','chrome.pricingFees':'मोल आनी शुल्क','chrome.tokensWallet':'टोकन वॉलेट','chrome.tagline':'भारताचो लायव्ह निर्मात्यांचो बाजार. एक आसन बुक करून एकठांय वेळ घालोवात.','chrome.voice':'तुमचो आवाज, सगळ्या जगाक।','chrome.goodbye':'आतां येता, परत मेळचें.','chrome.comeAgain':'परत येयात!','chrome.roadMotto':'सुरक्षीत चालोवात.','chrome.madeWith':'मोग आनी कटिंग चायेन केल्लें.'
},
mai: {
'chrome.marketplace':'मार्केटप्लेस','chrome.wiki':'विकी','chrome.pricing':'मूल्य','chrome.ideas':'विचार','chrome.bazaar':'बजार','chrome.creators':'सर्जक','chrome.company':'कम्पनी','chrome.explore':'खोजू','chrome.liveStreaming':'लाइव स्ट्रीमिंग','chrome.findPeople':'लोक केँ खोजू','chrome.exploreMarketplace':'मार्केटप्लेस देखू','chrome.startSelling':'बेचब शुरू करू','chrome.creatorDashboard':'सर्जक डैशबोर्ड','chrome.payouts':'भुगतान','chrome.safety':'सुरक्षा','chrome.about':'हमर विषयमे','chrome.careers':'रोजगार','chrome.contact':'सम्पर्क','chrome.privacy':'गोपनीयता','chrome.cookies':'कुकी','chrome.refunds':'रकम वापसी','chrome.marketplaceTerms':'मार्केटप्लेसक शर्त','chrome.consultationTerms':'परामर्शक शर्त','chrome.acceptableUse':'स्वीकार्य उपयोग','chrome.recordingConsent':'रिकॉर्डिङ सहमति','chrome.biometricData':'बायोमेट्रिक डाटा','chrome.dmca':'DMCA सूचना','chrome.communityGuidelines':'समुदाय निर्देश','chrome.childSafety':'बच्चाक सुरक्षा','chrome.grievance':'शिकायत','chrome.contactReport':'सम्पर्क आ रिपोर्ट','chrome.pricingFees':'मूल्य आ शुल्क','chrome.tokensWallet':'टोकन वॉलेट','chrome.tagline':'भारतक लाइव सर्जक बजार। एक सीट बुक कऽ संग समय बिताउ।','chrome.voice':'अहाँक आवाज, संसार धरि।','chrome.goodbye':'एखन लेल विदा, फेर भेटब।','chrome.comeAgain':'फेर आउ!','chrome.roadMotto':'सुरक्षित गाड़ी चलाउ।','chrome.madeWith':'प्रेम आ कटिंग चाय सँ बनल।'
},
doi: {
'chrome.marketplace':'मार्केटप्लेस','chrome.wiki':'विकी','chrome.pricing':'कीमत','chrome.ideas':'विचार','chrome.bazaar':'बजार','chrome.creators':'रचनाकार','chrome.company':'कंपनी','chrome.explore':'तलाश करो','chrome.liveStreaming':'लाइव स्ट्रीमिंग','chrome.findPeople':'लोकें गी खोजो','chrome.exploreMarketplace':'मार्केटप्लेस दिक्खो','chrome.startSelling':'बेचना शुरू करो','chrome.creatorDashboard':'रचनाकार डैशबोर्ड','chrome.payouts':'भुगतान','chrome.safety':'सुरक्षा','chrome.about':'साढ़े बारे च','chrome.careers':'नौकरी','chrome.contact':'संपर्क','chrome.privacy':'निजता','chrome.cookies':'कुकीज','chrome.refunds':'पैसे वापिस','chrome.marketplaceTerms':'मार्केटप्लेस शर्तां','chrome.consultationTerms':'सलाह शर्तां','chrome.acceptableUse':'मान्य इस्तेमाल','chrome.recordingConsent':'रिकॉर्डिंग रजामंदी','chrome.biometricData':'बायोमेट्रिक डेटा','chrome.dmca':'DMCA सूचना','chrome.communityGuidelines':'समुदाय निर्देश','chrome.childSafety':'बाल सुरक्षा','chrome.grievance':'शिकायत','chrome.contactReport':'संपर्क ते रिपोर्ट','chrome.pricingFees':'कीमत ते फीस','chrome.tokensWallet':'टोकन बटुआ','chrome.tagline':'भारत दा लाइव रचनाकार बजार। इक सीट बुक करो ते कट्ठे समां बिताओ।','chrome.voice':'तुंदा आवाज, दुनिया तगर।','chrome.goodbye':'हून आस्तै अलविदा, फ्ही मिलगे।','chrome.comeAgain':'फ्ही आओ!','chrome.roadMotto':'सुरक्षित गड्डी चलाओ।','chrome.madeWith':'प्यार ते कटिंग चा कन्नै बनाया।'
},
ur: {
'chrome.marketplace':'مارکیٹ پلیس','chrome.wiki':'وِکی','chrome.pricing':'قیمت','chrome.ideas':'خیالات','chrome.bazaar':'بازار','chrome.creators':'تخلیق کار','chrome.company':'کمپنی','chrome.explore':'دریافت کریں','chrome.liveStreaming':'لائیو اسٹریمنگ','chrome.findPeople':'لوگ تلاش کریں','chrome.exploreMarketplace':'مارکیٹ پلیس دیکھیں','chrome.startSelling':'فروخت شروع کریں','chrome.creatorDashboard':'تخلیق کار ڈیش بورڈ','chrome.payouts':'ادائیگیاں','chrome.safety':'حفاظت','chrome.about':'ہمارے بارے میں','chrome.careers':'ملازمتیں','chrome.contact':'رابطہ','chrome.privacy':'رازداری','chrome.cookies':'کوکیز','chrome.refunds':'رقم واپسی','chrome.marketplaceTerms':'مارکیٹ پلیس کی شرائط','chrome.consultationTerms':'مشاورت کی شرائط','chrome.acceptableUse':'قابل قبول استعمال','chrome.recordingConsent':'ریکارڈنگ کی رضامندی','chrome.biometricData':'بایومیٹرک ڈیٹا','chrome.dmca':'DMCA اطلاع','chrome.communityGuidelines':'کمیونٹی رہنما اصول','chrome.childSafety':'بچوں کی حفاظت','chrome.grievance':'شکایت','chrome.contactReport':'رابطہ اور رپورٹ','chrome.pricingFees':'قیمت اور فیس','chrome.tokensWallet':'ٹوکن والیٹ','chrome.tagline':'بھارت کا لائیو تخلیق کار بازار۔ ایک نشست بک کریں اور ساتھ وقت گزاریں۔','chrome.voice':'آپ کی آواز، دنیا تک۔','chrome.goodbye':'ابھی کے لیے خدا حافظ، پھر ملاقات ہوگی۔','chrome.comeAgain':'پھر آئیے!','chrome.roadMotto':'محفوظ ڈرائیو کریں۔','chrome.madeWith':'محبت اور کٹنگ چائے سے بنایا گیا۔'
},
pa: {
'chrome.marketplace':'ਮਾਰਕੀਟਪਲੇਸ','chrome.wiki':'ਵਿਕੀ','chrome.pricing':'ਕੀਮਤ','chrome.ideas':'ਵਿਚਾਰ','chrome.bazaar':'ਬਾਜ਼ਾਰ','chrome.creators':'ਸਿਰਜਣਹਾਰ','chrome.company':'ਕੰਪਨੀ','chrome.explore':'ਖੋਜੋ','chrome.liveStreaming':'ਲਾਈਵ ਸਟ੍ਰੀਮਿੰਗ','chrome.findPeople':'ਲੋਕ ਲੱਭੋ','chrome.exploreMarketplace':'ਮਾਰਕੀਟਪਲੇਸ ਵੇਖੋ','chrome.startSelling':'ਵੇਚਣਾ ਸ਼ੁਰੂ ਕਰੋ','chrome.creatorDashboard':'ਸਿਰਜਣਹਾਰ ਡੈਸ਼ਬੋਰਡ','chrome.payouts':'ਭੁਗਤਾਨ','chrome.safety':'ਸੁਰੱਖਿਆ','chrome.about':'ਸਾਡੇ ਬਾਰੇ','chrome.careers':'ਕਰੀਅਰ','chrome.contact':'ਸੰਪਰਕ','chrome.privacy':'ਪਰਦੇਦਾਰੀ','chrome.cookies':'ਕੂਕੀਜ਼','chrome.refunds':'ਰਕਮ ਵਾਪਸੀ','chrome.marketplaceTerms':'ਮਾਰਕੀਟਪਲੇਸ ਦੀਆਂ ਸ਼ਰਤਾਂ','chrome.consultationTerms':'ਸਲਾਹ ਦੀਆਂ ਸ਼ਰਤਾਂ','chrome.acceptableUse':'ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਵਰਤੋਂ','chrome.recordingConsent':'ਰਿਕਾਰਡਿੰਗ ਸਹਿਮਤੀ','chrome.biometricData':'ਬਾਇਓਮੈਟ੍ਰਿਕ ਡਾਟਾ','chrome.dmca':'DMCA ਸੂਚਨਾ','chrome.communityGuidelines':'ਭਾਈਚਾਰਕ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼','chrome.childSafety':'ਬੱਚਿਆਂ ਦੀ ਸੁਰੱਖਿਆ','chrome.grievance':'ਸ਼ਿਕਾਇਤ','chrome.contactReport':'ਸੰਪਰਕ ਅਤੇ ਰਿਪੋਰਟ','chrome.pricingFees':'ਕੀਮਤ ਅਤੇ ਫੀਸ','chrome.tokensWallet':'ਟੋਕਨ ਵਾਲਿਟ','chrome.tagline':'ਭਾਰਤ ਦਾ ਲਾਈਵ ਸਿਰਜਣਹਾਰ ਬਾਜ਼ਾਰ। ਇੱਕ ਸੀਟ ਬੁੱਕ ਕਰੋ ਅਤੇ ਇਕੱਠੇ ਸਮਾਂ ਬਿਤਾਓ।','chrome.voice':'ਤੁਹਾਡੀ ਆਵਾਜ਼, ਦੁਨੀਆ ਤੱਕ।','chrome.goodbye':'ਹੁਣ ਲਈ ਅਲਵਿਦਾ, ਫਿਰ ਮਿਲਾਂਗੇ।','chrome.comeAgain':'ਫਿਰ ਆਓ!','chrome.roadMotto':'ਸੁਰੱਖਿਅਤ ਗੱਡੀ ਚਲਾਓ।','chrome.madeWith':'ਪਿਆਰ ਅਤੇ ਕਟਿੰਗ ਚਾਹ ਨਾਲ ਬਣਾਇਆ।'
}
} as const;
