/** Tamil and Telugu chrome drafts; native speaker review required. */
export const chromeTamilTelugu = {
  ta: {
    'chrome.marketplace':'சந்தை','chrome.wiki':'விக்கி','chrome.pricing':'விலை','chrome.ideas':'யோசனைகள்','chrome.bazaar':'பஜார்','chrome.creators':'படைப்பாளர்கள்','chrome.company':'நிறுவனம்','chrome.explore':'ஆராயுங்கள்','chrome.liveStreaming':'நேரலை ஒளிபரப்பு','chrome.findPeople':'உங்கள் மக்களைக் கண்டறியுங்கள்','chrome.exploreMarketplace':'சந்தையைப் பாருங்கள்','chrome.startSelling':'விற்பனையைத் தொடங்குங்கள்','chrome.creatorDashboard':'படைப்பாளர் பலகை','chrome.payouts':'பணம் பெறுதல்','chrome.safety':'பாதுகாப்பு','chrome.about':'எங்களைப் பற்றி','chrome.careers':'வேலைவாய்ப்புகள்','chrome.contact':'தொடர்பு','chrome.privacy':'தனியுரிமைக் கொள்கை','chrome.cookies':'குக்கீகள்','chrome.refunds':'பணத்திரும்பப் பெறுதல்','chrome.marketplaceTerms':'சந்தை விதிமுறைகள்','chrome.consultationTerms':'ஆலோசனை விதிமுறைகள்','chrome.acceptableUse':'ஏற்றுக்கொள்ளத்தக்க பயன்பாடு','chrome.recordingConsent':'பதிவு மற்றும் ஒப்புதல்','chrome.biometricData':'உயிரளவுத் தரவு','chrome.dmca':'DMCA','chrome.communityGuidelines':'சமூக வழிகாட்டுதல்கள்','chrome.childSafety':'குழந்தைகள் பாதுகாப்பு','chrome.grievance':'குறைதீர்','chrome.contactReport':'தொடர்பு மற்றும் புகார்','chrome.pricingFees':'விலையும் கட்டணங்களும்','chrome.tokensWallet':'டோக்கன்கள் மற்றும் பணப்பை','chrome.tagline':'இந்தியாவின் நேரலை படைப்பாளர் சந்தை. ஒரு இருக்கையை முன்பதிவு செய்து ஒன்றாக நேரம் செலவிடுங்கள்.','chrome.voice':'உங்கள் குரல் உலகைச் சென்றடையட்டும்.','chrome.goodbye':'இப்போதைக்கு விடைபெறுகிறோம், மீண்டும் சந்திப்போம்.','chrome.comeAgain':'மீண்டும் வாருங்கள்.','chrome.roadMotto':'பாதுகாப்பாக வாகனம் ஓட்டுங்கள்.','chrome.madeWith':'அன்புடனும் கட்டிங் தேநீருடனும் உருவாக்கப்பட்டது.',
  },
  te: {
    'chrome.marketplace':'మార్కెట్‌ప్లేస్','chrome.wiki':'వికీ','chrome.pricing':'ధరలు','chrome.ideas':'ఆలోచనలు','chrome.bazaar':'బజార్','chrome.creators':'క్రియేటర్లు','chrome.company':'కంపెనీ','chrome.explore':'చూడండి','chrome.liveStreaming':'లైవ్ స్ట్రీమింగ్','chrome.findPeople':'మీ వారిని కనుగొనండి','chrome.exploreMarketplace':'మార్కెట్‌ప్లేస్ చూడండి','chrome.startSelling':'అమ్మకం ప్రారంభించండి','chrome.creatorDashboard':'క్రియేటర్ డ్యాష్‌బోర్డ్','chrome.payouts':'చెల్లింపులు','chrome.safety':'భద్రత','chrome.about':'మా గురించి','chrome.careers':'ఉద్యోగాలు','chrome.contact':'సంప్రదించండి','chrome.privacy':'గోప్యతా విధానం','chrome.cookies':'కుకీలు','chrome.refunds':'వాపసులు','chrome.marketplaceTerms':'మార్కెట్‌ప్లేస్ నిబంధనలు','chrome.consultationTerms':'సలహా సేవా నిబంధనలు','chrome.acceptableUse':'ఆమోదయోగ్యమైన వినియోగం','chrome.recordingConsent':'రికార్డింగ్ మరియు సమ్మతి','chrome.biometricData':'బయోమెట్రిక్ సమాచారం','chrome.dmca':'DMCA','chrome.communityGuidelines':'సమాజ మార్గదర్శకాలు','chrome.childSafety':'పిల్లల భద్రత','chrome.grievance':'ఫిర్యాదు పరిష్కారం','chrome.contactReport':'సంప్రదింపు మరియు నివేదిక','chrome.pricingFees':'ధరలు మరియు రుసుములు','chrome.tokensWallet':'టోకెన్లు మరియు వాలెట్','chrome.tagline':'భారతదేశపు లైవ్ క్రియేటర్ మార్కెట్. ఒక సీటు బుక్ చేసుకుని కలిసి సమయం గడపండి.','chrome.voice':'మీ స్వరం ప్రపంచానికి చేరాలి.','chrome.goodbye':'ఇప్పటికి వీడ్కోలు, మళ్లీ కలుద్దాం.','chrome.comeAgain':'మళ్లీ రండి.','chrome.roadMotto':'సురక్షితంగా వాహనం నడపండి.','chrome.madeWith':'ప్రేమతో, కట్టింగ్ చాయ్‌తో తయారు చేయబడింది.',
  },
} as const;
