/** Native chrome copy for Bodo, Meitei/Manipuri, and Santali. */
export const chromeScripts = {
  brx: {
    'chrome.marketplace':'मार्केटप्लेस','chrome.wiki':'विकि','chrome.pricing':'दाम','chrome.ideas':'आइडिया','chrome.bazaar':'बाजार','chrome.creators':'क्रियेटरफोर','chrome.company':'कम्पानि','chrome.explore':'नाय','chrome.liveStreaming':'लाइभ स्ट्रीमिं','chrome.findPeople':'मानसिफोरखौ मोन','chrome.exploreMarketplace':'मार्केटप्लेस नाय','chrome.startSelling':'बेचनाय जागाय','chrome.creatorDashboard':'क्रियेटर ड्यासबोर्ड','chrome.payouts':'पेयआउट','chrome.safety':'रैखाथि','chrome.about':'आबाउट','chrome.careers':'करियार','chrome.contact':'सम्पर्क','chrome.privacy':'गोपोनियता','chrome.cookies':'कुकिज','chrome.refunds':'रिफन्ड','chrome.marketplaceTerms':'मार्केटप्लेस नियम','chrome.consultationTerms':'परामर्श नियम','chrome.acceptableUse':'स्वीकार्य बाहायनाय','chrome.recordingConsent':'रेकर्डिं अनुमोदन','chrome.biometricData':'बायोमेट्रिक डाटा','chrome.dmca':'DMCA','chrome.communityGuidelines':'कम्युनिटि गाइडलाइन','chrome.childSafety':'बच्चानि रैखाथि','chrome.grievance':'अभियोग दैथाय','chrome.contactReport':'सम्पर्क आरो रिपोर्ट','chrome.pricingFees':'दाम आरो फी','chrome.tokensWallet':'टोकन आरो वालेट','chrome.tagline':'भारतनि लाइभ क्रियेटर बाजार। मोनसे सिट बुक खालाम आरो लोगोव सम हो।','chrome.voice':'नोंनि राव संसारसिम','chrome.goodbye':'दानियाव थां, फैसे मिलोगोन','chrome.comeAgain':'फिन फै','chrome.roadMotto':'सावधानै जाबाय','chrome.madeWith':'मोजां आरो कटिं चाइजों सोरजायनाय','chrome.home':'आव','chrome.mainNav':'गोदान नेभिगेसन','chrome.menu':'मेनु','chrome.login':'लग इन','chrome.signup':'साइन अप','chrome.dashboard':'ड्यासबोर्ड','chrome.signout':'साइन आउट','chrome.chooseLanguage':'राव सायख','chrome.footerNav':'फुटार नेभिगेसन','chrome.legal':'कानुनि','chrome.help':'मदद','chrome.terms':'नियम'
  },
  mni: {
    'chrome.marketplace':'ꯃꯥꯔꯀꯦꯠꯄ꯭ꯂꯦꯁ','chrome.wiki':'ꯋꯤꯀꯤ','chrome.pricing':'ꯃꯨꯜꯌ','chrome.ideas':'ꯑꯥꯏꯗꯤꯌꯥ','chrome.bazaar':'ꯕꯥꯖꯥꯔ','chrome.creators':'ꯀ꯭ꯔꯤꯑꯦꯇꯔꯁꯤꯡ','chrome.company':'ꯀꯝꯄꯥꯅꯤ','chrome.explore':'ꯌꯦꯡꯉꯨ','chrome.liveStreaming':'ꯂꯥꯏꯕ ꯁ꯭ꯇ꯭ꯔꯤꯃꯤꯡ','chrome.findPeople':'ꯃꯤꯁꯤꯡꯕꯨ ꯐꯪꯉꯨ','chrome.exploreMarketplace':'ꯃꯥꯔꯀꯦꯠꯄ꯭ꯂꯦꯁ ꯌꯦꯡꯉꯨ','chrome.startSelling':'ꯁꯦꯜꯂꯤꯡ ꯍꯧꯖꯤꯛ','chrome.creatorDashboard':'ꯀ꯭ꯔꯤꯑꯦꯇꯔ ꯗꯦꯁꯕꯣꯔꯗ','chrome.payouts':'ꯄꯦꯑꯣꯠ','chrome.safety':'ꯁꯤꯐꯝ','chrome.about':'ꯑꯥꯕꯥꯎꯠ','chrome.careers':'ꯀꯔꯤꯌꯔ','chrome.contact':'ꯀꯟꯇꯦꯛ','chrome.privacy':'ꯄ꯭ꯔꯥꯏꯕꯦꯁꯤ','chrome.cookies':'ꯀꯨꯀꯤꯁ','chrome.refunds':'ꯔꯤꯐꯟꯗ','chrome.marketplaceTerms':'ꯃꯥꯔꯀꯦꯠꯄ꯭ꯂꯦꯁ ꯅꯤꯌꯝ','chrome.consultationTerms':'ꯀꯟꯁꯜꯇꯦꯁꯟ ꯅꯤꯌꯝ','chrome.acceptableUse':'ꯌꯥꯅꯕ ꯁꯤꯖꯤꯟꯅꯕ','chrome.recordingConsent':'ꯔꯤꯀꯣꯔꯗꯤꯡ ꯑꯅꯨꯃꯇꯤ','chrome.biometricData':'ꯕꯥꯏꯑꯣꯃꯦꯇ꯭ꯔꯤꯛ ꯗꯥꯇꯥ','chrome.dmca':'DMCA','chrome.communityGuidelines':'ꯀꯝꯌꯨꯅꯤꯇꯤ ꯒꯥꯏꯗꯂꯥꯏꯟ','chrome.childSafety':'ꯆꯥꯏꯜꯗ ꯁꯤꯐꯝ','chrome.grievance':'ꯒ꯭ꯔꯤꯕꯥꯟꯁ','chrome.contactReport':'ꯀꯟꯇꯦꯛ ꯑꯃꯗꯤ ꯔꯤꯄꯣꯔꯠ','chrome.pricingFees':'ꯃꯨꯜꯌ ꯑꯃꯗꯤ ꯐꯤ','chrome.tokensWallet':'ꯇꯣꯀꯦꯟ ꯑꯃꯗꯤ ꯋꯥꯂꯦꯠ','chrome.tagline':'ꯏꯟꯗꯤꯌꯥꯒꯤ ꯂꯥꯏꯕ ꯀ꯭ꯔꯤꯑꯦꯇꯔ ꯕꯥꯖꯥꯔ. ꯁꯤꯠ ꯑꯃꯥ ꯕꯨꯛ ꯇꯧꯗꯨꯅ ꯑꯃꯗꯤ ꯃꯇꯝ ꯄꯨꯟꯅ ꯄꯥꯡꯊꯣꯛꯎ.','chrome.voice':'ꯅꯪꯒꯤ ꯋꯥꯍꯪ ꯂꯥꯏꯕ ꯌꯥꯑꯣꯕ','chrome.goodbye':'ꯍꯧꯖꯤꯛ ꯐꯥꯑꯣ, ꯐꯤꯔꯥꯜ ꯎꯅꯒꯅꯤ','chrome.comeAgain':'ꯍꯜꯂꯛꯄ ꯑꯣꯏ','chrome.roadMotto':'ꯂꯝꯗ ꯁꯤꯐꯝ ꯇꯧꯕꯤꯌꯨ','chrome.madeWith':'ꯅꯨꯡꯁꯤꯕ ꯑꯃꯗꯤ ꯆꯥ ꯁꯥꯡꯒ ꯁꯤꯖꯤꯟꯅ ꯁꯣꯔꯖꯕ','chrome.home':'ꯍꯣꯝ','chrome.mainNav':'ꯃꯥꯏꯅ ꯅꯦꯕꯤꯒꯦꯁꯟ','chrome.menu':'ꯃꯦꯅꯨ','chrome.login':'ꯂꯣꯒ ꯏꯟ','chrome.signup':'ꯁꯥꯏꯟ ꯑꯞ','chrome.dashboard':'ꯗꯦꯁꯕꯣꯔꯗ','chrome.signout':'ꯁꯥꯏꯟ ꯑꯥꯎꯠ','chrome.chooseLanguage':'ꯂꯣꯟ ꯈꯅꯣ','chrome.footerNav':'ꯐꯨꯠꯔ ꯅꯦꯕꯤꯒꯦꯁꯟ','chrome.legal':'ꯂꯥꯏꯒꯜ','chrome.help':'ꯃꯇꯦꯡ','chrome.terms':'ꯅꯤꯌꯝ'
  },
  sat: {
    'chrome.marketplace':'ᱢᱟᱨᱠᱮᱴᱯᱞᱮᱥ','chrome.wiki':'ᱣᱤᱠᱤ','chrome.pricing':'ᱫᱟᱢ','chrome.ideas':'ᱵᱤᱪᱟᱹᱨ','chrome.bazaar':'ᱵᱟᱡᱟᱨ','chrome.creators':'ᱠᱨᱤᱭᱮᱴᱚᱨ ᱠᱚ','chrome.company':'ᱠᱚᱢᱯᱟᱹᱱᱤ','chrome.explore':'ᱧᱮᱞ ᱢᱮ','chrome.liveStreaming':'ᱞᱟᱭᱤᱵ ᱥᱴᱨᱤᱢᱤᱝ','chrome.findPeople':'ᱦᱚᱲ ᱠᱚ ᱧᱟᱢ ᱢᱮ','chrome.exploreMarketplace':'ᱢᱟᱨᱠᱮᱴᱯᱞᱮᱥ ᱧᱮᱞ ᱢᱮ','chrome.startSelling':'ᱵᱤᱠᱨᱤ ᱮᱦᱚᱵ ᱢᱮ','chrome.creatorDashboard':'ᱠᱨᱤᱭᱮᱴᱚᱨ ᱰᱮᱥᱵᱚᱨᱰ','chrome.payouts':'ᱯᱮᱭᱟᱣᱴ','chrome.safety':'ᱵᱟᱹᱪᱟᱹᱣ','chrome.about':'ᱵᱟᱵᱚᱛ','chrome.careers':'ᱠᱟᱹᱨᱤᱭᱟᱹᱨ','chrome.contact':'ᱡᱚᱯᱚᱲ','chrome.privacy':'ᱜᱚᱯᱚᱱᱤᱭᱟ','chrome.cookies':'ᱠᱩᱠᱤᱥ','chrome.refunds':'ᱯᱟᱭᱥᱟ ᱨᱩᱦᱟᱹᱲ','chrome.marketplaceTerms':'ᱢᱟᱨᱠᱮᱴᱯᱞᱮᱥ ᱱᱤᱭᱚᱢ','chrome.consultationTerms':'ᱯᱨᱚᱢᱚᱨᱥᱚ ᱱᱤᱭᱚᱢ','chrome.acceptableUse':'ᱥᱟᱹᱯᱷᱟ ᱵᱮᱵᱚᱦᱟᱨ','chrome.recordingConsent':'ᱨᱮᱠᱚᱨᱰᱤᱝ ᱥᱟᱢᱚᱛᱤ','chrome.biometricData':'ᱵᱟᱭᱚᱢᱮᱴᱨᱤᱠ ᱰᱟᱴᱟ','chrome.dmca':'DMCA','chrome.communityGuidelines':'ᱠᱚᱢᱭᱩᱱᱤᱴᱤ ᱜᱟᱭᱰᱞᱟᱭᱤᱱ','chrome.childSafety':'ᱦᱚᱲᱢᱚ ᱥᱩᱨᱟᱹᱠᱷᱭᱟ','chrome.grievance':'ᱟᱵᱚᱫᱽ','chrome.contactReport':'ᱡᱚᱯᱚᱲ ᱟᱨ ᱨᱤᱯᱚᱨᱴ','chrome.pricingFees':'ᱫᱟᱢ ᱟᱨ ᱯᱷᱤ','chrome.tokensWallet':'ᱴᱚᱠᱮᱱ ᱟᱨ ᱣᱟᱞᱮᱴ','chrome.tagline':'ᱵᱷᱟᱨᱚᱛᱨᱮᱱ ᱞᱟᱭᱤᱵ ᱠᱨᱤᱭᱮᱴᱚᱨ ᱵᱟᱡᱟᱨ. ᱢᱤᱫ ᱥᱤᱴ ᱵᱩᱠ ᱢᱮ ᱟᱨ ᱢᱤᱫ ᱥᱟᱶᱛᱟᱣ ᱚᱠᱛᱚ ᱮᱢ ᱢᱮ.','chrome.voice':'ᱟᱢᱟᱜ ᱠᱚᱛᱷᱟ ᱡᱟᱜᱟᱛ ᱛᱮ','chrome.goodbye':'ᱱᱤᱛᱚᱜ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱭ, ᱫᱩᱵᱟᱹᱨᱟ ᱧᱮᱞ ᱢᱮ','chrome.comeAgain':'ᱫᱩᱵᱟᱹᱨᱟ ᱦᱤᱡᱩᱜ ᱢᱮ','chrome.roadMotto':'ᱨᱟᱥᱛᱟᱨᱮ ᱥᱟᱵᱫᱷᱟᱱ ᱢᱮ','chrome.madeWith':'ᱫᱟᱹᱭᱟ ᱟᱨ ᱠᱟᱴᱤᱝ ᱪᱟᱭ ᱛᱮ ᱵᱟᱹᱭᱥᱟᱹᱣ','chrome.home':'ᱚᱲᱟᱜ','chrome.mainNav':'ᱢᱩᱬ ᱱᱮᱵᱤᱜᱮᱥᱚᱱ','chrome.menu':'ᱢᱮᱱᱩ','chrome.login':'ᱞᱚᱜᱤᱱ','chrome.signup':'ᱥᱟᱭᱤᱱ ᱟᱯ','chrome.dashboard':'ᱰᱮᱥᱵᱚᱨᱰ','chrome.signout':'ᱥᱟᱭᱤᱱ ᱟᱣᱩᱴ','chrome.chooseLanguage':'ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ','chrome.footerNav':'ᱯᱷᱩᱴᱟᱨ ᱱᱮᱵᱤᱜᱮᱥᱚᱱ','chrome.legal':'ᱵᱟᱹᱭᱫᱷᱟᱱᱤᱠ','chrome.help':'ᱜᱚᱲᱚ','chrome.terms':'ᱱᱤᱭᱚᱢ'
  }
} as const;
