export const chromeSouthEast = {
kn: {
'chrome.marketplace':'ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್','chrome.wiki':'ವಿಕಿ','chrome.pricing':'ಬೆಲೆ','chrome.ideas':'ಆಲೋಚನೆಗಳು','chrome.bazaar':'ಬಜಾರ್','chrome.creators':'ಸೃಜನಕಾರರು','chrome.company':'ಕಂಪನಿ','chrome.explore':'ಅನ್ವೇಷಿಸಿ','chrome.liveStreaming':'ಲೈವ್ ಸ್ಟ್ರೀಮಿಂಗ್','chrome.findPeople':'ಜನರನ್ನು ಹುಡುಕಿ','chrome.exploreMarketplace':'ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್ ಅನ್ವೇಷಿಸಿ','chrome.startSelling':'ಮಾರಾಟ ಆರಂಭಿಸಿ','chrome.creatorDashboard':'ಸೃಜನಕಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್','chrome.payouts':'ಪಾವತಿಗಳು','chrome.safety':'ಸುರಕ್ಷತೆ','chrome.about':'ನಮ್ಮ ಬಗ್ಗೆ','chrome.careers':'ಉದ್ಯೋಗಾವಕಾಶಗಳು','chrome.contact':'ಸಂಪರ್ಕ','chrome.privacy':'ಗೌಪ್ಯತೆ','chrome.cookies':'ಕುಕೀಸ್','chrome.refunds':'ಹಣ ಮರುಪಾವತಿ','chrome.marketplaceTerms':'ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್ ನಿಯಮಗಳು','chrome.consultationTerms':'ಸಮಾಲೋಚನೆ ನಿಯಮಗಳು','chrome.acceptableUse':'ಸ್ವೀಕಾರಾರ್ಹ ಬಳಕೆ','chrome.recordingConsent':'ರೆಕಾರ್ಡಿಂಗ್ ಒಪ್ಪಿಗೆ','chrome.biometricData':'ಬಯೋಮೆಟ್ರಿಕ್ ಮಾಹಿತಿ','chrome.dmca':'DMCA ಸೂಚನೆ','chrome.communityGuidelines':'ಸಮುದಾಯ ಮಾರ್ಗಸೂಚಿಗಳು','chrome.childSafety':'ಮಕ್ಕಳ ಸುರಕ್ಷತೆ','chrome.grievance':'ದೂರು','chrome.contactReport':'ಸಂಪರ್ಕ ಮತ್ತು ವರದಿ','chrome.pricingFees':'ಬೆಲೆ ಮತ್ತು ಶುಲ್ಕಗಳು','chrome.tokensWallet':'ಟೋಕನ್ ವಾಲೆಟ್','chrome.tagline':'ಭಾರತದ ಲೈವ್ ಸೃಜನಕಾರರ ಬಜಾರ್. ಒಂದು ಆಸನ ಕಾಯ್ದಿರಿಸಿ, ಜೊತೆಯಲ್ಲಿ ಸಮಯ ಕಳೆಯಿರಿ.','chrome.voice':'ನಿಮ್ಮ ಧ್ವನಿ, ಜಗತ್ತಿನೆಡೆಗೆ.','chrome.goodbye':'ಈಗ ವಿದಾಯ, ಮತ್ತೆ ಭೇಟಿಯಾಗೋಣ.','chrome.comeAgain':'ಮತ್ತೆ ಬನ್ನಿ!','chrome.roadMotto':'ಸುರಕ್ಷಿತವಾಗಿ ಚಾಲನೆ ಮಾಡಿ.','chrome.madeWith':'ಪ್ರೀತಿ ಮತ್ತು ಕಟಿಂಗ್ ಚಹಾದಿಂದ ತಯಾರಿಸಲಾಗಿದೆ.'
},
ml: {
'chrome.marketplace':'മാർക്കറ്റ്‌പ്ലേസ്','chrome.wiki':'വിക്കി','chrome.pricing':'വില','chrome.ideas':'ആശയങ്ങൾ','chrome.bazaar':'ബസാർ','chrome.creators':'സ്രഷ്ടാക്കൾ','chrome.company':'കമ്പനി','chrome.explore':'പര്യവേക്ഷണം','chrome.liveStreaming':'ലൈവ് സ്ട്രീമിംഗ്','chrome.findPeople':'ആളുകളെ കണ്ടെത്തുക','chrome.exploreMarketplace':'മാർക്കറ്റ്‌പ്ലേസ് കാണുക','chrome.startSelling':'വിൽപ്പന തുടങ്ങുക','chrome.creatorDashboard':'സ്രഷ്ടാവ് ഡാഷ്ബോർഡ്','chrome.payouts':'പേയ്മെന്റുകൾ','chrome.safety':'സുരക്ഷ','chrome.about':'ഞങ്ങളെക്കുറിച്ച്','chrome.careers':'തൊഴിൽ അവസരങ്ങൾ','chrome.contact':'ബന്ധപ്പെടുക','chrome.privacy':'സ്വകാര്യത','chrome.cookies':'കുക്കികൾ','chrome.refunds':'പണം തിരികെ','chrome.marketplaceTerms':'മാർക്കറ്റ്‌പ്ലേസ് നിബന്ധനകൾ','chrome.consultationTerms':'കൺസൾട്ടേഷൻ നിബന്ധനകൾ','chrome.acceptableUse':'അംഗീകരിക്കാവുന്ന ഉപയോഗം','chrome.recordingConsent':'റെക്കോർഡിങ് സമ്മതം','chrome.biometricData':'ബയോമെട്രിക് ഡാറ്റ','chrome.dmca':'DMCA അറിയിപ്പ്','chrome.communityGuidelines':'കമ്മ്യൂണിറ്റി മാർഗ്ഗനിർദ്ദേശങ്ങൾ','chrome.childSafety':'കുട്ടികളുടെ സുരക്ഷ','chrome.grievance':'പരാതി','chrome.contactReport':'ബന്ധപ്പെടലും റിപ്പോർട്ടും','chrome.pricingFees':'വിലയും ഫീസും','chrome.tokensWallet':'ടോക്കൺ വാലറ്റ്','chrome.tagline':'ഇന്ത്യയുടെ ലൈവ് സ്രഷ്ടാക്കളുടെ ബസാർ. ഒരു സീറ്റ് ബുക്ക് ചെയ്ത് ഒരുമിച്ച് സമയം ചെലവഴിക്കൂ.','chrome.voice':'നിങ്ങളുടെ ശബ്ദം, ലോകത്തേക്ക്.','chrome.goodbye':'ഇപ്പോൾ വിട, വീണ്ടും കാണാം.','chrome.comeAgain':'വീണ്ടും വരൂ!','chrome.roadMotto':'സുരക്ഷിതമായി ഡ്രൈവ് ചെയ്യൂ.','chrome.madeWith':'സ്നേഹവും കട്ടിങ് ചായയും ചേർത്ത് നിർമ്മിച്ചത്.'
},
or: {
'chrome.marketplace':'ମାର୍କେଟପ୍ଲେସ୍','chrome.wiki':'ଉଇକି','chrome.pricing':'ମୂଲ୍ୟ','chrome.ideas':'ଧାରଣା','chrome.bazaar':'ବଜାର','chrome.creators':'ସୃଷ୍ଟିକର୍ତ୍ତା','chrome.company':'କମ୍ପାନୀ','chrome.explore':'ଅନୁସନ୍ଧାନ','chrome.liveStreaming':'ଲାଇଭ୍ ଷ୍ଟ୍ରିମିଂ','chrome.findPeople':'ଲୋକ ଖୋଜନ୍ତୁ','chrome.exploreMarketplace':'ମାର୍କେଟପ୍ଲେସ୍ ଦେଖନ୍ତୁ','chrome.startSelling':'ବିକ୍ରି ଆରମ୍ଭ କରନ୍ତୁ','chrome.creatorDashboard':'ସୃଷ୍ଟିକର୍ତ୍ତା ଡ୍ୟାସବୋର୍ଡ','chrome.payouts':'ପେମେଣ୍ଟ','chrome.safety':'ସୁରକ୍ଷା','chrome.about':'ଆମ ବିଷୟରେ','chrome.careers':'କ୍ୟାରିଅର୍','chrome.contact':'ଯୋଗାଯୋଗ','chrome.privacy':'ଗୋପନୀୟତା','chrome.cookies':'କୁକିଜ୍','chrome.refunds':'ଟଙ୍କା ଫେରସ୍ତ','chrome.marketplaceTerms':'ମାର୍କେଟପ୍ଲେସ୍ ନିୟମ','chrome.consultationTerms':'ପରାମର୍ଶ ନିୟମ','chrome.acceptableUse':'ଗ୍ରହଣଯୋଗ୍ୟ ବ୍ୟବହାର','chrome.recordingConsent':'ରେକର୍ଡିଂ ସମ୍ମତି','chrome.biometricData':'ବାୟୋମେଟ୍ରିକ୍ ତଥ୍ୟ','chrome.dmca':'DMCA ସୂଚନା','chrome.communityGuidelines':'ସମୁଦାୟ ନିର୍ଦ୍ଦେଶାବଳୀ','chrome.childSafety':'ଶିଶୁ ସୁରକ୍ଷା','chrome.grievance':'ଅଭିଯୋଗ','chrome.contactReport':'ଯୋଗାଯୋଗ ଓ ରିପୋର୍ଟ','chrome.pricingFees':'ମୂଲ୍ୟ ଓ ଶୁଳ୍କ','chrome.tokensWallet':'ଟୋକନ୍ ୱାଲେଟ୍','chrome.tagline':'ଭାରତର ଲାଇଭ୍ ସୃଷ୍ଟିକର୍ତ୍ତା ବଜାର। ଏକ ସିଟ୍ ବୁକ୍ କରି ଏକାଠି ସମୟ କାଟନ୍ତୁ।','chrome.voice':'ଆପଣଙ୍କ ସ୍ୱର, ସାରା ବିଶ୍ୱକୁ।','chrome.goodbye':'ଏବେ ବିଦାୟ, ପୁଣି ଦେଖା ହେବ।','chrome.comeAgain':'ପୁଣି ଆସନ୍ତୁ!','chrome.roadMotto':'ସୁରକ୍ଷିତ ଭାବେ ଗାଡ଼ି ଚଳାନ୍ତୁ।','chrome.madeWith':'ଭଲପାଇବା ଓ କଟିଂ ଚାହାରେ ତିଆରି।'
},
sa: {
'chrome.marketplace':'विपणिप्रदेशः','chrome.wiki':'विकी','chrome.pricing':'मूल्यम्','chrome.ideas':'विचाराः','chrome.bazaar':'विपणिः','chrome.creators':'स्रष्टारः','chrome.company':'कम्पनी','chrome.explore':'अन्वेषयतु','chrome.liveStreaming':'प्रत्यक्षप्रवाहः','chrome.findPeople':'जनान् अन्वेषयतु','chrome.exploreMarketplace':'विपणिप्रदेशम् अन्वेषयतु','chrome.startSelling':'विक्रयं प्रारभताम्','chrome.creatorDashboard':'स्रष्टृ-पटलम्','chrome.payouts':'भुगतानानि','chrome.safety':'सुरक्षा','chrome.about':'अस्माकं विषये','chrome.careers':'वृत्तयः','chrome.contact':'सम्पर्कः','chrome.privacy':'गोपनीयता','chrome.cookies':'कुकीज्','chrome.refunds':'धनप्रतिदानम्','chrome.marketplaceTerms':'विपणि-नियमाः','chrome.consultationTerms':'परामर्श-नियमाः','chrome.acceptableUse':'स्वीकार्यः उपयोगः','chrome.recordingConsent':'अङ्कन-सम्मतिः','chrome.biometricData':'जैवमितीय-दत्तांशः','chrome.dmca':'DMCA सूचना','chrome.communityGuidelines':'समुदाय-निर्देशाः','chrome.childSafety':'बालसुरक्षा','chrome.grievance':'शिकायत्','chrome.contactReport':'सम्पर्कः प्रतिवेदनं च','chrome.pricingFees':'मूल्यं शुल्कं च','chrome.tokensWallet':'टोकन-पुटकम्','chrome.tagline':'भारतस्य प्रत्यक्षस्रष्टृणां विपणिः। आसनं आरक्ष्य सह समयं यापयतु।','chrome.voice':'भवतः स्वरः, विश्वं प्रति।','chrome.goodbye':'अधुना नमस्कारः, पुनः मिलामः।','chrome.comeAgain':'पुनरागच्छतु!','chrome.roadMotto':'सुरक्षितं वाहनं चालयतु।','chrome.madeWith':'प्रेम्णा कटिङ्ग्-चायेन च निर्मितम्।'
}
} as const;
