export const chromeNorthRtl = {
as: {
'chrome.marketplace':'মাৰ্কেটপ্লেচ','chrome.wiki':'ৱিকি','chrome.pricing':'মূল্য','chrome.ideas':'ধাৰণা','chrome.bazaar':'বজাৰ','chrome.creators':'সৃষ্টিকৰ্তা','chrome.company':'কোম্পানী','chrome.explore':'অন্বেষণ','chrome.liveStreaming':'লাইভষ্ট্ৰিমিং','chrome.findPeople':'মানুহ বিচাৰক','chrome.exploreMarketplace':'মাৰ্কেটপ্লেচ অন্বেষণ কৰক','chrome.startSelling':'বিক্ৰী আৰম্ভ কৰক','chrome.creatorDashboard':'সৃষ্টিকৰ্তা ডেশ্বব’ৰ্ড','chrome.payouts':'পেমেণ্ট লাভ','chrome.safety':'সুৰক্ষা','chrome.about':'আমাৰ বিষয়ে','chrome.careers':'চাকৰি','chrome.contact':'যোগাযোগ','chrome.privacy':'গোপনীয়তা','chrome.cookies':'কুকীসমূহ','chrome.refunds':'ধন ঘূৰাই দিয়া','chrome.marketplaceTerms':'মাৰ্কেটপ্লেচৰ চৰ্ত','chrome.consultationTerms':'পৰামৰ্শৰ চৰ্ত','chrome.acceptableUse':'গ্ৰহণযোগ্য ব্যৱহাৰ','chrome.recordingConsent':'ৰেকৰ্ডিঙৰ সন্মতি','chrome.biometricData':'বায়’মেট্ৰিক তথ্য','chrome.dmca':'DMCA জাননী','chrome.communityGuidelines':'সম্প্ৰদায়ৰ নিৰ্দেশনা','chrome.childSafety':'শিশু সুৰক্ষা','chrome.grievance':'অভিযোগ','chrome.contactReport':'যোগাযোগ আৰু প্ৰতিবেদন','chrome.pricingFees':'মূল্য আৰু মাচুল','chrome.tokensWallet':'টোকেন ৱালেট','chrome.tagline':'ভাৰতৰ লাইভ সৃষ্টিকৰ্তাৰ বজাৰ। এটা আসন বুক কৰি একেলগে সময় কটাওক।','chrome.voice':'আপোনাৰ কণ্ঠ, সমগ্ৰ বিশ্বলৈ।','chrome.goodbye':'এতিয়াৰ বাবে বিদায়, আকৌ দেখা হ’ব।','chrome.comeAgain':'আকৌ আহিব!','chrome.roadMotto':'নিৰাপদে গাড়ী চলাওক।','chrome.madeWith':'ভালপোৱা আৰু কাটিং চাহেৰে নিৰ্মিত।'
},
ne: {
'chrome.marketplace':'मार्केटप्लेस','chrome.wiki':'विकी','chrome.pricing':'मूल्य','chrome.ideas':'विचार','chrome.bazaar':'बजार','chrome.creators':'सिर्जनाकर्ता','chrome.company':'कम्पनी','chrome.explore':'अन्वेषण','chrome.liveStreaming':'लाइभस्ट्रिमिङ','chrome.findPeople':'मानिस खोज्नुहोस्','chrome.exploreMarketplace':'मार्केटप्लेस हेर्नुहोस्','chrome.startSelling':'बिक्री सुरु गर्नुहोस्','chrome.creatorDashboard':'सिर्जनाकर्ता ड्यासबोर्ड','chrome.payouts':'भुक्तानी प्राप्ति','chrome.safety':'सुरक्षा','chrome.about':'हाम्रो बारेमा','chrome.careers':'करियर','chrome.contact':'सम्पर्क','chrome.privacy':'गोपनीयता','chrome.cookies':'कुकीहरू','chrome.refunds':'फिर्ता रकम','chrome.marketplaceTerms':'मार्केटप्लेसका सर्त','chrome.consultationTerms':'परामर्शका सर्त','chrome.acceptableUse':'स्वीकार्य प्रयोग','chrome.recordingConsent':'रेकर्डिङ सहमति','chrome.biometricData':'बायोमेट्रिक डेटा','chrome.dmca':'DMCA सूचना','chrome.communityGuidelines':'समुदाय निर्देशिका','chrome.childSafety':'बाल सुरक्षा','chrome.grievance':'गुनासो','chrome.contactReport':'सम्पर्क र रिपोर्ट','chrome.pricingFees':'मूल्य र शुल्क','chrome.tokensWallet':'टोकन वालेट','chrome.tagline':'भारतको लाइभ सिर्जनाकर्ता बजार। एउटा सिट बुक गरेर सँगै समय बिताउनुहोस्।','chrome.voice':'तपाईंको आवाज, संसारसम्म।','chrome.goodbye':'अहिलेलाई बिदा, फेरि भेटौँला।','chrome.comeAgain':'फेरि आउनुहोस्!','chrome.roadMotto':'सुरक्षित रूपमा गाडी चलाउनुहोस्।','chrome.madeWith':'माया र कटिङ चियासँग बनाइएको।'
},
ks: {
'chrome.marketplace':'مارکیٹ پلیس','chrome.wiki':'وِکی','chrome.pricing':'قٕیمت','chrome.ideas':'خیالات','chrome.bazaar':'بازار','chrome.creators':'تخلیق کار','chrome.company':'کمپنی','chrome.explore':'دٔیژھو','chrome.liveStreaming':'لائیو اسٹریمِنگ','chrome.findPeople':'لوگ ژھٲریو','chrome.exploreMarketplace':'مارکیٹ پلیس دٔیژھو','chrome.startSelling':'فروخت شروع کٔریو','chrome.creatorDashboard':'تخلیق کار ڈیش بورڈ','chrome.payouts':'ادائیگی','chrome.safety':'حفاظت','chrome.about':'ہمسٕنٛد متعلق','chrome.careers':'مٲملإت','chrome.contact':'رٲبطہ','chrome.privacy':'رازدٲری','chrome.cookies':'کوکیز','chrome.refunds':'رقم واپسی','chrome.marketplaceTerms':'مارکیٹ پلیس شرٲط','chrome.consultationTerms':'مشورٕ شرٲط','chrome.acceptableUse':'قابل قبول استعمال','chrome.recordingConsent':'ریکارڈنگ رضامندی','chrome.biometricData':'بایومیٹرک ڈیٹا','chrome.dmca':'DMCA نوٹس','chrome.communityGuidelines':'برادری ہدایات','chrome.childSafety':'بچن ہٕنٛد حفاظت','chrome.grievance':'شکایت','chrome.contactReport':'رٲبطہ تہ رپورٹ','chrome.pricingFees':'قٕیمت تہ فیس','chrome.tokensWallet':'ٹوکن والٹ','chrome.tagline':'ہِندوستانُک لائیو تخلیق کار بازار۔ یِک سیٹ بُک کٔریو تہ یِکٹھٕ وقت گُزارِیو۔','chrome.voice':'تُہند آواز، دُنیا تام۔','chrome.goodbye':'فی الحال خدا حافظ، وُچھو پھر۔','chrome.comeAgain':'دوبارٕ یِیو!','chrome.roadMotto':'محفوظ طریقس سڑکَس پٮ۪ٹھ چلإیو۔','chrome.madeWith':'محبت تہ کٹنگ چائے سٲتھ بناومُت۔'
},
sd: {
'chrome.marketplace':'مارڪيٽ پليس','chrome.wiki':'وڪي','chrome.pricing':'قيمت','chrome.ideas':'خيال','chrome.bazaar':'بازار','chrome.creators':'تخليقڪار','chrome.company':'ڪمپني','chrome.explore':'ڳوليو','chrome.liveStreaming':'لائيو اسٽريمنگ','chrome.findPeople':'ماڻهو ڳوليو','chrome.exploreMarketplace':'مارڪيٽ پليس ڏسو','chrome.startSelling':'وڪرو شروع ڪريو','chrome.creatorDashboard':'تخليقڪار ڊيش بورڊ','chrome.payouts':'ادائيگيون','chrome.safety':'حفاظت','chrome.about':'اسان بابت','chrome.careers':'نوڪريون','chrome.contact':'رابطو','chrome.privacy':'رازداري','chrome.cookies':'ڪوڪيز','chrome.refunds':'رقم واپسي','chrome.marketplaceTerms':'مارڪيٽ پليس جون شرطون','chrome.consultationTerms':'صلاح جون شرطون','chrome.acceptableUse':'قابل قبول استعمال','chrome.recordingConsent':'رڪارڊنگ جي رضامندي','chrome.biometricData':'بايوميٽرڪ ڊيٽا','chrome.dmca':'DMCA اطلاع','chrome.communityGuidelines':'برادري جون هدايتون','chrome.childSafety':'ٻارن جي حفاظت','chrome.grievance':'شڪايت','chrome.contactReport':'رابطو ۽ رپورٽ','chrome.pricingFees':'قيمت ۽ فيس','chrome.tokensWallet':'ٽوڪن والٽ','chrome.tagline':'ڀارت جي لائيو تخليقڪارن جو بازار. هڪ سيٽ بڪ ڪريو ۽ گڏ وقت گذاريو.','chrome.voice':'توهان جو آواز، دنيا تائين.','chrome.goodbye':'هاڻي لاءِ خدا حافظ، وري ملنداسين.','chrome.comeAgain':'وري اچو!','chrome.roadMotto':'محفوظ ڊرائيو ڪريو.','chrome.madeWith':'محبت ۽ ڪٽنگ چانهه سان ٺهيل۔'
}
} as const;
