/** Reviewed source copy for the India creator landing page.
 * Keep both dictionaries flat and key-identical so locale workers can translate
 * every visible string without changing page structure.
 */
export const sourceHinglish = {
  skip: 'Skip to main content',
  eyebrow: 'India creator ticket window',
  heroTitle: 'Fanbase hai? Apna show jamao.',
  heroBody: 'Apni skill, apni story, apna time — fans ko invite karo aur apne terms par book lo.',
  heroPrimary: 'Start creating free',
  heroSecondary: 'See earning formats',
  heroTicket: 'Your page. Your price. Your people.',
  liveEyebrow: 'FORMAT 01 · LIVE',
  liveTitle: 'Livestream ko event banao.',
  liveBody: 'A live class, a watch party, a rehearsal, a puja — ticket lagao, room kholo, fans se milo.',
  liveCta: 'Plan a live event',
  liveMeta: 'Ticketed · Hosted online',
  oneEyebrow: 'FORMAT 02 · 1:1',
  oneTitle: 'Apna time, one fan at a time.',
  oneBody: 'Online video meetup ke liye slots kholo. Advice, practice, stories ya bas ek focused conversation.',
  oneCta: 'Offer a 1:1 session',
  oneMeta: 'Private · Video meetup',
  showcaseEyebrow: 'THE BIG SCREEN',
  showcaseTitle: 'Jo screen par hota hai, woh connection ban sakta hai.',
  showcaseBody: 'Music, makeup, gaming, recipes, dance, devotion — fans already dekh rahe hain. Ab unhe ek room do.',
  showcaseLabel: 'Live room / Saturday 8:00 PM',
  showcaseButton: 'Explore the marketplace',
  meetupEyebrow: 'YOUR CALENDAR, YOUR RULES',
  meetupTitle: 'Aapka 1:1 corner.',
  meetupBody: 'Availability set karo, format samjhao, aur har booking se pehle clear expectations rakho. Online only, always.',
  meetupNote: 'Online video mulaqat. Apna time, apni boundaries.',
  ideasEyebrow: 'CONTENT SE OFFER TAK',
  ideasTitle: 'Aap kya host karoge?',
  ideaOneTitle: 'Dance adda',
  ideaOneBody: 'Choreography, feedback, practice room.',
  ideaTwoTitle: 'Ghar ka swaad',
  ideaTwoBody: 'Recipe live, regional thali, kitchen hacks.',
  ideaThreeTitle: 'Study buddy',
  ideaThreeBody: 'Revision sprint, language practice, exam pep talk.',
  ideaFourTitle: 'Style desk',
  ideaFourBody: 'Look breakdowns, draping, thrift finds.',
  journeyEyebrow: 'HOW IT WORKS',
  journeyTitle: 'Poster se booking tak — four easy moves.',
  stepOne: 'Create',
  stepOneBody: 'Apna creator page aur offer likho.',
  stepTwo: 'Price',
  stepTwoBody: 'Ticket ya session price choose karo.',
  stepThree: 'Share',
  stepThreeBody: 'Link apni community ko bhejo.',
  stepFour: 'Host',
  stepFourBody: 'Room kholo, time do, apna show chalao.',
  bookingEyebrow: 'FOR YOUR FANS',
  bookingTitle: 'Fan ko booking kaise dikhegi?',
  bookingBody: 'Ek clear page. Ek date. Ek seat. Payment ke baad unhe room ka raasta milta hai.',
  bookingCta: 'Browse real listings',
  bookingTicket: 'BOOKING PASS',
  bookingLive: 'LIVE EVENT',
  bookingSeat: '1 seat reserved',
  bookingOnline: 'Online · India',
  calcEyebrow: 'THE MATH, CLEARLY',
  calcTitle: 'Apna gross estimate dekho.',
  calcBody: 'Inputs badlo aur dekho ticketed events ya 1:1 bookings se kitna gross ban sakta hai.',
  calcLiveLabel: 'Live Ticket price per participant',
  calcAudienceLabel: 'Audience per event',
  calcEventsLabel: 'Events per month',
  calcOneLabel: '1:1 or 1:many Price per participant',
  calcBookingsLabel: 'Bookings per month',
  calcLiveTotal: 'Live event gross',
  calcOneTotal: '1:1 gross',
  calcTotal: 'Combined gross estimate',
  calcDisclaimer: 'Illustrative gross before platform fees, taxes, refunds and other costs. Not a promise of earnings.',
  calcPricingNote: 'Planning example in INR; actual listing pricing and checkout quotes follow the current pricing guide.',
  boundariesEyebrow: 'GOOD TO KNOW',
  boundariesTitle: 'Clear boundaries make better rooms.',
  faqOneQ: 'Do I need a big following?',
  faqOneA: 'No. Start with one useful offer and share it with the people who already care about your work.',
  faqTwoQ: 'Is this an in-person booking?',
  faqTwoA: 'No. Live events and 1:1 sessions happen online. Keep your listing and expectations specific.',
  faqThreeQ: 'When do I get paid?',
  faqThreeA: 'Payout timing and eligible methods are shown in your creator dashboard and the applicable terms.',
  faqFourQ: 'Can I set my own boundaries?',
  faqFourA: 'Yes. Choose your format, availability, price and what the session includes before publishing.',
  closeEyebrow: 'YOUR TURN',
  closeTitle: 'Apni awaaz ko ticket do.',
  closeBody: 'Aaj ek offer likho. Kal apna first room kholo.',
  closeCta: 'Create your free listing',
  ariaDecorative: 'Decorative',
  ariaCalculator: 'Gross earnings estimate calculator',
  ariaFaq: 'Frequently asked questions',
} as const;

/** English review source. Hinglish remains the default display language. */
export const sourceEnglish = {
  ...sourceHinglish,
  eyebrow: 'India creator ticket window', heroTitle: 'Have a fanbase? Start your show.', heroBody: 'Your skill, your story, your time — invite fans and take bookings on your terms.', heroPrimary: 'Start creating free', heroSecondary: 'See earning formats', heroTicket: 'Your page. Your price. Your people.',
  liveEyebrow: 'FORMAT 01 · LIVE', liveTitle: 'Turn your livestream into an event.', liveBody: 'A live class, watch party, rehearsal, puja — add a ticket, open the room, meet your fans.', liveCta: 'Plan a live event', liveMeta: 'Ticketed · Hosted online', oneEyebrow: 'FORMAT 02 · 1:1', oneTitle: 'Your time, one fan at a time.', oneBody: 'Open slots for an online video meetup. Advice, practice, stories or one focused conversation.', oneCta: 'Offer a 1:1 session', oneMeta: 'Private · Video meetup',
  showcaseEyebrow: 'THE BIG SCREEN', showcaseTitle: 'What happens on screen can become a connection.', showcaseBody: 'Music, makeup, gaming, recipes, dance, devotion — people are already watching. Give them a room.', showcaseLabel: 'Live room / Saturday 8:00 PM', showcaseButton: 'Explore the marketplace', meetupEyebrow: 'YOUR CALENDAR, YOUR RULES', meetupTitle: 'Your 1:1 corner.', meetupBody: 'Set your availability, explain the format, and keep expectations clear before every booking. Online only, always.', meetupNote: 'Online video meetups, with clear boundaries.',
  ideasEyebrow: 'FROM CONTENT TO OFFER', ideasTitle: 'What will you host?', ideaOneTitle: 'Dance adda', ideaOneBody: 'Choreography, feedback, practice room.', ideaTwoTitle: 'Home flavours', ideaTwoBody: 'Recipe live, regional thali, kitchen hacks.', ideaThreeTitle: 'Study buddy', ideaThreeBody: 'Revision sprint, language practice, exam pep talk.', ideaFourTitle: 'Style desk', ideaFourBody: 'Look breakdowns, draping, thrift finds.', journeyEyebrow: 'HOW IT WORKS', journeyTitle: 'From poster to booking — four easy moves.', stepOne: 'Create', stepOneBody: 'Write your creator page and offer.', stepTwo: 'Price', stepTwoBody: 'Choose your ticket or session price.', stepThree: 'Share', stepThreeBody: 'Send the link to your community.', stepFour: 'Host', stepFourBody: 'Open the room, give your time, run your show.',
  bookingEyebrow: 'FOR YOUR FANS', bookingTitle: 'What does booking look like for a fan?', bookingBody: 'One clear page. One date. One seat. After payment, they get the route to the room.', bookingCta: 'Browse real listings', bookingTicket: 'BOOKING PASS', bookingLive: 'LIVE EVENT', bookingSeat: '1 seat reserved', bookingOnline: 'Online · India', calcEyebrow: 'THE MATH, CLEARLY', calcTitle: 'See your gross estimate.', calcBody: 'Change the inputs to see what ticketed events or 1:1 bookings could gross.', calcLiveLabel: 'Live Ticket price per participant', calcAudienceLabel: 'Audience per event', calcEventsLabel: 'Events per month', calcOneLabel: '1:1 or 1:many Price per participant', calcBookingsLabel: 'Bookings per month', calcLiveTotal: 'Live event gross', calcOneTotal: '1:1 gross', calcTotal: 'Combined gross estimate', calcDisclaimer: 'Illustrative gross before platform fees, taxes, refunds and other costs. Not a promise of earnings.', boundariesEyebrow: 'GOOD TO KNOW', boundariesTitle: 'Clear boundaries make better rooms.',
  faqOneQ: 'Do I need a big following?', faqOneA: 'No. Start with one useful offer and share it with people who already care about your work.', faqTwoQ: 'Is this an in-person booking?', faqTwoA: 'No. Live events and 1:1 sessions happen online. Keep your listing and expectations specific.', faqThreeQ: 'When do I get paid?', faqThreeA: 'Payout timing and eligible methods are shown in your creator dashboard and the applicable terms.', faqFourQ: 'Can I set my own boundaries?', faqFourA: 'Yes. Choose your format, availability, price and what the session includes before publishing.', closeEyebrow: 'YOUR TURN', closeTitle: 'Put a ticket on your voice.', closeBody: 'Write one offer today. Open your first room tomorrow.', closeCta: 'Create your free listing', ariaDecorative: 'Decorative', ariaCalculator: 'Gross earnings estimate calculator', ariaFaq: 'Frequently asked questions', calcPricingNote: 'Planning example in INR; actual listing pricing and checkout quotes follow the current pricing guide.',
} as const;

export type IndiaLandingKey = keyof typeof sourceEnglish;
