import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const H=vi.hoisted(()=>({enabled:true}));
vi.mock('../src/routes/config',()=>({readConfig:async()=>({hdfcSmsEnabled:H.enabled})}));
import {fixture,request} from './hdfc_test_db';
import {hdfcPublicOrder as order,hdfcPublicStatus as status,hdfcPublicClaim as claim,hdfcPublicRecheck as recheck} from '../src/routes/hdfc_sms_public';
import {hdfcSmsIncoming} from '../src/routes/hdfc_sms_payments';
import {sha256Hex,hmacSha256Hex} from '../src/lib/payments/types';
let f:ReturnType<typeof fixture>,now:number; const token='a'.repeat(64),other='b'.repeat(64);
beforeEach(()=>{now=1800000000500;vi.spyOn(Date,'now').mockImplementation(()=>now);f=fixture();H.enabled=true});
afterEach(()=>{f.sql.close();vi.restoreAllMocks()});
function req(path:string,body?:unknown,bearer=token){const r=request(path,body);r.headers.set('authorization',`Bearer ${bearer}`);r.headers.set('cf-connecting-ip','192.0.2.1');return r}
type E={ok:true;enabled:boolean;intent:{intent_id:string;status:string;reason_code:string|null;matching_mode:string;amount_paise:number;currency:string;reference_revision:number;confirmed_at:number|null;upi_url?:string;recover_until:number}}
const json=(r:Response)=>r.json() as Promise<E>;
async function create(key=crypto.randomUUID(),bearer=token){return order(req('/order',{request_key:key},bearer),f.env)}
async function read(id:string,bearer=token){return status(req(`/status?intent_id=${id}`,undefined,bearer),f.env)}
async function incoming(reference='000123456789',amount='1.00',received:number|string=now){const sender='VM-HDFCBK',message=`Rs.${amount} credited to A/c XX1234 from VPA payer@icici (UPI ${reference}).`,b={device_id:'test-device',sender,message,received_at:typeof received==='string'?received:new Date(received).toISOString(),sim_slot:-1,message_hash:'',nonce:crypto.randomUUID(),sent_at:new Date(now).toISOString(),signature:''};b.message_hash=await sha256Hex(`${sender}|${message}|${b.received_at}`);b.signature=await hmacSha256Hex(f.env.HDFC_SMS_DEVICE_SECRET!,[b.device_id,sender,message,b.received_at,b.sim_slot,b.message_hash,b.nonce,b.sent_at].join('\n'));return hdfcSmsIncoming(request('/incoming',b),f.env)}
const claims=()=>f.sql.prepare('SELECT count(*) n FROM hdfc_sms_smoke_receipts WHERE claimed_intent_id IS NOT NULL').get()?.n;
describe('public QR and payment-reference confirmation',()=>{
 it('creates a QR without payer details and isolates capability ownership',async()=>{for(const route of [order,status,claim,recheck])expect((await route(request('/x',{request_key:crypto.randomUUID()}),f.env)).status).toBe(401);const r=await create(),v=await json(r);expect(r.status).toBe(200);expect(v.intent).toMatchObject({status:'pending',matching_mode:'bank_reference',amount_paise:100,currency:'INR',reference_revision:0});expect(v.intent.upi_url).toContain('tr=AV');const otherIntent=await create(crypto.randomUUID(),other);expect(otherIntent.status).toBe(200);expect((await json(otherIntent)).intent.intent_id).not.toBe(v.intent.intent_id);expect((await read(v.intent.intent_id,other)).status).toBe(404)});
 it('waits for a signed bank SMS, then atomically verifies one 12-digit reference',async()=>{const id=(await json(await create())).intent.intent_id;expect((await json(await read(id))).intent.status).toBe('pending');expect((await claim(req('/claim',{intent_id:id,bank_reference:'bad',expected_reference_revision:0}),f.env)).status).toBe(400);await incoming();expect((await json(await read(id))).intent.status).toBe('pending');const verified=await claim(req('/claim',{intent_id:id,bank_reference:'000123456789',expected_reference_revision:0}),f.env);expect(verified.status).toBe(200);expect((await json(verified)).intent).toMatchObject({status:'confirmed',confirmed_at:now});expect(claims()).toBe(1)});
 it('does not confirm an unmatched reference and rejects reuse after settlement',async()=>{const a=(await json(await create())).intent.intent_id;await incoming('000123456780');expect((await claim(req('/claim',{intent_id:a,bank_reference:'000123456789',expected_reference_revision:0}),f.env)).status).toBe(200);expect((await json(await read(a))).intent.status).toBe('pending');await claim(req('/claim',{intent_id:a,bank_reference:'000123456780',expected_reference_revision:1}),f.env);expect((await json(await read(a))).intent.status).toBe('confirmed');const b=(await json(await create())).intent.intent_id;expect((await claim(req('/claim',{intent_id:b,bank_reference:'000123456780',expected_reference_revision:0}),f.env)).status).toBe(409);expect((await json(await read(b))).intent.status).toBe('pending')});
 it('keeps waiting when SMS is delayed and recheck can complete it',async()=>{const id=(await json(await create())).intent.intent_id;H.enabled=false;await incoming();H.enabled=true;expect((await json(await read(id))).intent.status).toBe('pending');await claim(req('/claim',{intent_id:id,bank_reference:'000123456789',expected_reference_revision:0}),f.env);expect((await json(await recheck(req('/recheck',{intent_id:id}),f.env))).intent.status).toBe('confirmed')});
 it('supports retry and refresh without creating a second attempt',async()=>{const key=crypto.randomUUID(),first=(await json(await create(key))).intent;expect((await json(await create(key))).intent.intent_id).toBe(first.intent_id);expect((await json(await read(first.intent_id))).intent.intent_id).toBe(first.intent_id);H.enabled=false;expect((await json(await create(key))).intent.intent_id).toBe(first.intent_id)});
 it('does not expose references across capabilities and preserves legacy fields',async()=>{const id=(await json(await create())).intent.intent_id;expect((await read(id,other)).status).toBe(404);const body=JSON.stringify(await json(await read(id)));expect(body).not.toContain(token);expect(body).not.toContain('payer_reference')});
});
