// GENERATED by scripts/export-zine-tokens.mjs — DO NOT EDIT BY HAND.
// Imported by tailwind.config.ts as `theme.extend`.
module.exports = {
  "colors": {
    "paper": "var(--zine-paper)",
    "paper2": "var(--zine-paper2)",
    "card": "var(--zine-card)",
    "ink": "var(--zine-ink)",
    "inkSoft": "var(--zine-inkSoft)",
    "inkMute": "var(--zine-inkMute)",
    "placeholder": "var(--zine-placeholder)",
    "blue": "var(--zine-blue)",
    "blueInk": "var(--zine-blueInk)",
    "lime": "var(--zine-lime)",
    "coral": "var(--zine-coral)",
    "lilac": "var(--zine-lilac)",
    "mint": "var(--zine-mint)",
    "mintInk": "var(--zine-mintInk)",
    "tape": "var(--zine-tape)",
    "coralMark": "var(--zine-coralMark)",
    "blueMark": "var(--zine-blueMark)"
  },
  "borderRadius": {
    "zine": "22px",
    "zineSm": "16px",
    "zineField": "18px",
    "zineBadge": "11px"
  },
  "borderWidth": {
    "zine": "2.5px",
    "zineLg": "3px"
  },
  "boxShadow": {
    "zine": "var(--zine-shadow)",
    "zine-sm": "var(--zine-shadowSm)",
    "zine-xs": "var(--zine-shadowXs)",
    "zine-pressed": "var(--zine-shadowPressed)",
    "zine-focus": "var(--zine-shadowFocus)",
    "zine-error": "var(--zine-shadowError)"
  },
  "fontFamily": {
    "display": [
      "Fredoka",
      "system-ui",
      "sans-serif"
    ],
    "body": [
      "Nunito",
      "system-ui",
      "sans-serif"
    ],
    "mono": [
      "\"Space Mono\"",
      "ui-monospace",
      "monospace"
    ]
  },
  "transitionDuration": {
    "zine": "120ms",
    "zine-slow": "250ms"
  }
};
